#!/bin/bash

do_reboot() {
  info "Rebooting now..."
  systemctl reboot
  (sleep 120 && systemctl reboot --force > /dev/null 2>&1) &
  # If the previous reboot commands have failed for any reason, let's try differently
  (sleep 300 && reboot --force > /dev/null 2>&1) &
  # If the previous 2 reboot commands have failed for any reason, try the Magic SysRq
  # enable and send reboot request
  (sleep 600 && echo 1 > /proc/sys/kernel/sysrq && echo b > /proc/sysrq-trigger) &
  while true; do sleep 60; done
}
