#!/bin/sh

# shellcheck disable=SC1091
. /usr/libexec/os-helpers-fs

fsck_enabled() {
    # On flasher we don't run fsck
    # shellcheck disable=SC2154
    if [ "$bootparam_flasher" = "true" ]; then
        echo "[INFO] Flasher detected. We don't run fsck on the partitions when provisioning."
        return 1
    fi
    return 0
}

fsck_run() {
    cat > "/etc/e2fsck.conf" <<EOF
[options]
broken_system_clock=1
EOF

    # fsck uses mtab to see if a device is mounted
    if [ ! -e "/etc/mtab" ]; then
        ln -sf /proc/mounts /etc/mtab
    fi

    disk="$(get_state_path_from_label "pando-boot")"
    info "Running filesystem checks on partition pando-boot ($disk)"
    fsck.vfat -a -w "${disk}"
    disk="$(get_state_path_from_label "pando-rootA")"
    info "Running filesystem checks on partition pando-rootA ($disk)"
    fsck.ext4 -p "${disk}"
    disk="$(get_state_path_from_label "pando-rootB")"
    info "Running filesystem checks on partition pando-rootB ($disk)"
    fsck.ext4 -p "${disk}"
    disk="$(get_state_path_from_label "pando-state")"
    info "Running filesystem checks on partition pando-state ($disk)"
    fsck.ext4 -p "${disk}"
    disk="$(get_state_path_from_label "pando-data")"
    info "Running filesystem checks on partition pando-data ($disk)"
    fsck.ext4 -p "${disk}"
}
